language: python

env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34

matrix:
  allow_failures:
    - env: TOXENV=py27
    - env: TOXENV=py32
    - env: TOXENV=py33
    - env: TOXENV=py34

install:
  - pip install coveralls
  - pip install tox

script:
  - tox

after_success:
  - coverage combine
  - coveralls
