language: python

env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

matrix:
  allow_failures:
    - env: TOXENV=py35

install:
  - pip install coveralls
  - pip install 'virtualenv<14.0.0'
  - pip install tox

script:
  - tox

after_success:
  - coverage combine
  - coveralls
